@startuml etape-01-activite-affichage

title Étape 1 : Affichage des notes (boucle for)

start

:i = 1;

while (i <= 5 ?) is (oui)
  if (i == 1) then (oui)
    :note = note1;
  elseif (i == 2) then (oui)
    :note = note2;
  elseif (i == 3) then (oui)
    :note = note3;
  elseif (i == 4) then (oui)
    :note = note4;
  else (i == 5)
    :note = note5;
  endif
  
  :Afficher "Note i : note";
  :i = i + 1;
endwhile (non)

stop

@enduml
