@startuml
start
:Choisir un nombre secret entre 1 et 100;
repeat
  :Demander une proposition à l'utilisateur;
  if (Proposition = nombre secret ?) then (oui)
    :Afficher "Bravo, trouvé !";
    stop
  else (non)
    if (Proposition < nombre secret ?) then (oui)
      :Afficher "C'est plus grand";
    else (non)
      :Afficher "C'est plus petit";
    endif
  endif
repeat while (Proposition != nombre secret)
stop
@enduml
